# AUTO-GENERATED by /generate-schematic — do not edit manually.
# This file is replaced entirely each time the skill runs for a new circuit.
"""Communication blocks: RS-485 (MAX3485) and USB-UART (CP2102N)."""

from cad.schematic.sch_helpers import (
    CP2102N_PINS,
    MAX3485_PINS,
    USB_MICRO_PINS,
    c_pin,
    conn_1xn_pin,
    ic_pin,
    nc,
    r_pin,
    stub_label,
    stub_pwr,
)

FP_SOIC8 = "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm"
FP_R_0805 = "Resistor_SMD:R_0805_2012Metric"
FP_R_0603 = "Resistor_SMD:R_0603_1608Metric"
FP_CONN_1X04 = "Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical"
FP_C_0402 = "Capacitor_SMD:C_0402_1005Metric"
FP_QFN20 = "Package_DFN_QFN:QFN-20-1EP_4x4mm_P0.5mm_EP2.5x2.5mm"
FP_USB_MICRO = "Connector_USB:USB_Micro-B_Molex_47346-0001"


def place_rs485_block(sch, bx: int, by: int, pwr: dict) -> None:
    """Place RS-485 transceiver block."""
    u1_pos = (bx + 22, by + 20)
    u1 = sch.components.add("Interface_UART:MAX3485", "U1", "MAX3485", position=u1_pos)
    u1.footprint = FP_SOIC8

    stub_label(sch, ic_pin(u1_pos, MAX3485_PINS, 1), "RS485_RX", dx=-8)
    stub_label(sch, ic_pin(u1_pos, MAX3485_PINS, 2), "RS485_DE", dx=-8)
    stub_label(sch, ic_pin(u1_pos, MAX3485_PINS, 3), "RS485_DE", dx=-8)
    stub_label(sch, ic_pin(u1_pos, MAX3485_PINS, 4), "RS485_TX", dx=-8)
    stub_pwr(sch, ic_pin(u1_pos, MAX3485_PINS, 8), "power:+3V3", pwr, dy=-4)
    stub_pwr(sch, ic_pin(u1_pos, MAX3485_PINS, 5), "power:GND", pwr, dy=4)
    stub_label(sch, ic_pin(u1_pos, MAX3485_PINS, 6), "RS485_A", dx=6, rotation=180)
    stub_label(sch, ic_pin(u1_pos, MAX3485_PINS, 7), "RS485_B", dx=6, rotation=180)

    r1_pos = (bx + 44, by + 14)
    r1 = sch.components.add("Device:R", "R1", "120", position=r1_pos)
    r1.footprint = FP_R_0805
    stub_label(sch, r_pin(r1_pos, 2), "RS485_A", dx=-4)
    stub_label(sch, r_pin(r1_pos, 1), "RS485_B", dx=-4, dy=2)

    r2_pos = (bx + 54, by + 12)
    r2 = sch.components.add("Device:R", "R2", "560", position=r2_pos)
    r2.footprint = FP_R_0603
    stub_pwr(sch, r_pin(r2_pos, 2), "power:+3V3", pwr, dy=-4)
    stub_label(sch, r_pin(r2_pos, 1), "RS485_A", dx=-4, dy=2)

    r3_pos = (bx + 54, by + 28)
    r3 = sch.components.add("Device:R", "R3", "560", position=r3_pos)
    r3.footprint = FP_R_0603
    stub_label(sch, r_pin(r3_pos, 2), "RS485_B", dx=-4)
    stub_pwr(sch, r_pin(r3_pos, 1), "power:GND", pwr, dy=4)

    j3_pos = (bx + 66, by + 20)
    j3 = sch.components.add(
        "Connector_Generic:Conn_01x04", "J3", "RS485", position=j3_pos
    )
    j3.footprint = FP_CONN_1X04
    stub_label(sch, conn_1xn_pin(j3_pos, 4, 1), "RS485_A", dx=-6)
    stub_label(sch, conn_1xn_pin(j3_pos, 4, 2), "RS485_B", dx=-6)
    stub_label(sch, conn_1xn_pin(j3_pos, 4, 3), "RS485_DE", dx=-6)
    stub_pwr(sch, conn_1xn_pin(j3_pos, 4, 4), "power:GND", pwr, dx=-4, dy=0)

    c3_pos = (bx + 10, by + 8)
    c3 = sch.components.add("Device:C", "C3", "100nF", position=c3_pos)
    c3.footprint = FP_C_0402
    stub_pwr(sch, c_pin(c3_pos, 1), "power:+3V3", pwr, dy=-4)
    stub_pwr(sch, c_pin(c3_pos, 2), "power:GND", pwr, dy=4)


def place_usb_uart_block(sch, bx: int, by: int, pwr: dict) -> None:
    """Place USB-UART bridge block."""
    # Reason: y-offset +40 avoids J4.GND and U2.TXD sharing exact y-coordinate
    u2_pos = (bx + 36, by + 40)
    u2 = sch.components.add(
        "Interface_USB:CP2102N-Axx-xQFN20", "U2", "CP2102N", position=u2_pos
    )
    u2.footprint = FP_QFN20

    stub_pwr(sch, ic_pin(u2_pos, CP2102N_PINS, 6), "power:+3V3", pwr, dy=-4)
    stub_pwr(sch, ic_pin(u2_pos, CP2102N_PINS, 3), "power:GND", pwr, dy=4)
    stub_label(sch, ic_pin(u2_pos, CP2102N_PINS, 4), "USB_DP", dx=-6)
    stub_label(sch, ic_pin(u2_pos, CP2102N_PINS, 5), "USB_DM", dx=-6)
    stub_label(sch, ic_pin(u2_pos, CP2102N_PINS, 17), "UART_TX", dx=8, rotation=180)
    stub_label(sch, ic_pin(u2_pos, CP2102N_PINS, 18), "UART_RX", dx=8, rotation=180)

    used = {3, 4, 5, 6, 12, 17, 18, 21}
    for pin_num in range(1, 22):
        if pin_num not in used:
            nc(sch, ic_pin(u2_pos, CP2102N_PINS, pin_num))

    j4_pos = (bx + 6, by + 8)
    j4 = sch.components.add("Connector:USB_B_Micro", "J4", "USB_DEBUG", position=j4_pos)
    j4.footprint = FP_USB_MICRO

    stub_pwr(sch, ic_pin(j4_pos, USB_MICRO_PINS, 1), "power:+3V3", pwr, dx=6, dy=0)
    stub_label(sch, ic_pin(j4_pos, USB_MICRO_PINS, 3), "USB_DP", dx=6, rotation=180)
    stub_label(sch, ic_pin(j4_pos, USB_MICRO_PINS, 2), "USB_DM", dx=6, rotation=180)
    stub_pwr(sch, ic_pin(j4_pos, USB_MICRO_PINS, 5), "power:GND", pwr, dy=4)
    nc(sch, ic_pin(j4_pos, USB_MICRO_PINS, 4))
    nc(sch, ic_pin(j4_pos, USB_MICRO_PINS, 6))

    c4_pos = (bx + 54, by + 12)
    c4 = sch.components.add("Device:C", "C4", "100nF", position=c4_pos)
    c4.footprint = FP_C_0402
    stub_pwr(sch, c_pin(c4_pos, 1), "power:+3V3", pwr, dy=-4)
    stub_pwr(sch, c_pin(c4_pos, 2), "power:GND", pwr, dy=4)
