# AUTO-GENERATED by /generate-schematic — do not edit manually.
# This file is replaced entirely each time the skill runs for a new circuit.
"""Shared helpers for schematic block placement.

Pin offset calculations, power ref generators, and wiring utilities.
"""

Pos = tuple[int, int]

MAX3485_PINS: dict[int, Pos] = {
    1: (-8, -4),
    2: (-8, -2),
    3: (-8, 0),
    4: (-8, 4),
    5: (0, 12),
    6: (8, -6),
    7: (8, -2),
    8: (0, -12),
}

CP2102N_PINS: dict[int, Pos] = {
    1: (10, 8),
    2: (10, 6),
    3: (0, 22),
    4: (-10, -4),
    5: (-10, -6),
    6: (0, -22),
    7: (-2, -22),
    8: (-10, -8),
    9: (-10, -18),
    10: (-8, 18),
    11: (10, 2),
    12: (0, 22),
    13: (10, -6),
    14: (10, 0),
    15: (10, -12),
    16: (10, -14),
    17: (10, -16),
    18: (10, -18),
    19: (10, 12),
    20: (10, 10),
    21: (0, 22),
}

USB_MICRO_PINS: dict[int, Pos] = {
    1: (6, -4),
    2: (6, 2),
    3: (6, 0),
    4: (6, 4),
    5: (0, 8),
    6: (-2, 8),
}


def ic_pin(comp_pos: Pos, pins: dict[int, Pos], pin: int) -> Pos:
    """Get IC pin absolute grid position from component position and offset dict."""
    dx, dy = pins[pin]
    return (comp_pos[0] + dx, comp_pos[1] + dy)


def conn_1xn_pin(comp_pos: Pos, n_pins: int, pin_k: int) -> Pos:
    """Conn_01xN pin K position in grid units."""
    bx, by = comp_pos
    return (bx - 4, by - (n_pins - 2) + (pin_k - 1) * 2)


def conn_2x20_pin(comp_pos: Pos, pin_k: int) -> Pos:
    """Conn_02x20 pin K position (odd=left, even=right)."""
    bx, by = comp_pos
    if pin_k % 2 == 1:
        return (bx - 4, by - 18 + (pin_k - 1))
    return (bx + 6, by - 18 + (pin_k - 2))


def c_pin(comp_pos: Pos, pin: int) -> Pos:
    """Capacitor/polyfuse pin. Pin 1=top(-3), Pin 2=bottom(+3)."""
    bx, by = comp_pos
    return (bx, by - 3) if pin == 1 else (bx, by + 3)


def r_pin(comp_pos: Pos, pin: int) -> Pos:
    """Resistor pin (vertical). Pin 1=bottom(+3), Pin 2=top(-3)."""
    bx, by = comp_pos
    return (bx, by + 3) if pin == 1 else (bx, by - 3)


def q_pmos_pin(comp_pos: Pos, pin: str) -> Pos:
    """Q_PMOS_GSD pin position. pin='G'/'S'/'D'."""
    bx, by = comp_pos
    offsets = {"G": (-4, 0), "S": (2, 4), "D": (2, -4)}
    dx, dy = offsets[pin]
    return (bx + dx, by + dy)


def pwr_ref(pwr: dict) -> str:
    """Next unique #PWR reference."""
    ref = f"#PWR{pwr['n']:02d}"
    pwr["n"] += 1
    return ref


def flg_ref(pwr: dict) -> str:
    """Next unique #FLG reference."""
    ref = f"#FLG{pwr['flg']:02d}"
    pwr["flg"] += 1
    return ref


def add_pwr(sch, symbol: str, pos: Pos, pwr: dict, rotation: float = 0):
    """Add power symbol with auto-generated ref."""
    name = symbol.split(":")[-1]
    sch.components.add(symbol, pwr_ref(pwr), name, position=pos, rotation=rotation)


def add_flg(sch, pos: Pos, pwr: dict, rotation: float = 0):
    """Add PWR_FLAG with auto-generated ref."""
    sch.components.add(
        "power:PWR_FLAG",
        flg_ref(pwr),
        "PWR_FLAG",
        position=pos,
        rotation=rotation,
    )


def nc(sch, grid_pos: Pos) -> None:
    """Add no-connect at grid position (converts to mm)."""
    sch.no_connects.add(position=(grid_pos[0] * 1.27, grid_pos[1] * 1.27))


def stub_label(
    sch, pin: Pos, name: str, dx: int = -4, dy: int = 0, rotation: float = 0
) -> None:
    """Wire stub from pin to label."""
    end = (pin[0] + dx, pin[1] + dy)
    sch.add_wire(start=pin, end=end)
    sch.add_label(name, position=end, rotation=rotation)


def stub_pwr(
    sch, pin: Pos, symbol: str, pwr: dict, dx: int = 0, dy: int = -4
) -> None:
    """Wire stub from pin to power symbol."""
    end = (pin[0] + dx, pin[1] + dy)
    sch.add_wire(start=pin, end=end)
    add_pwr(sch, symbol, end, pwr)
