# AUTO-GENERATED by /generate-schematic — do not edit manually.
# This file is replaced entirely each time the skill runs for a new circuit.
"""I/O header blocks: I2C (with pull-ups), SPI, GPIO, and decoupling caps."""

from cad.schematic.sch_helpers import (
    c_pin,
    conn_1xn_pin,
    nc,
    r_pin,
    stub_label,
    stub_pwr,
)

FP_R_0603 = "Resistor_SMD:R_0603_1608Metric"
FP_CONN_1X04 = "Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical"
FP_CONN_1X06 = "Connector_PinHeader_2.54mm:PinHeader_1x06_P2.54mm_Vertical"
FP_CONN_1X08 = "Connector_PinHeader_2.54mm:PinHeader_1x08_P2.54mm_Vertical"
FP_C_0402 = "Capacitor_SMD:C_0402_1005Metric"


def place_io_block(sch, bx: int, by: int, pwr: dict) -> None:
    """Place I2C, SPI, and GPIO header blocks."""
    r4_pos = (bx + 6, by + 8)
    r4 = sch.components.add("Device:R", "R4", "2.2k", position=r4_pos)
    r4.footprint = FP_R_0603
    stub_pwr(sch, r_pin(r4_pos, 2), "power:+3V3", pwr, dy=-4)
    stub_label(sch, r_pin(r4_pos, 1), "SDA", dx=-4, dy=2)

    r5_pos = (bx + 14, by + 8)
    r5 = sch.components.add("Device:R", "R5", "2.2k", position=r5_pos)
    r5.footprint = FP_R_0603
    stub_pwr(sch, r_pin(r5_pos, 2), "power:+3V3", pwr, dy=-4)
    stub_label(sch, r_pin(r5_pos, 1), "SCL", dx=-4, dy=2)

    j5_pos = (bx + 26, by + 10)
    j5 = sch.components.add(
        "Connector_Generic:Conn_01x04", "J5", "I2C", position=j5_pos
    )
    j5.footprint = FP_CONN_1X04
    stub_pwr(sch, conn_1xn_pin(j5_pos, 4, 1), "power:+3V3", pwr, dx=-4, dy=0)
    stub_label(sch, conn_1xn_pin(j5_pos, 4, 2), "SDA", dx=-4)
    stub_label(sch, conn_1xn_pin(j5_pos, 4, 3), "SCL", dx=-4)
    stub_pwr(sch, conn_1xn_pin(j5_pos, 4, 4), "power:GND", pwr, dx=-4, dy=0)

    j6_pos = (bx + 44, by + 10)
    j6 = sch.components.add(
        "Connector_Generic:Conn_01x06", "J6", "SPI", position=j6_pos
    )
    j6.footprint = FP_CONN_1X06
    stub_pwr(sch, conn_1xn_pin(j6_pos, 6, 1), "power:+3V3", pwr, dx=-4, dy=0)
    stub_label(sch, conn_1xn_pin(j6_pos, 6, 2), "MOSI", dx=-4)
    stub_label(sch, conn_1xn_pin(j6_pos, 6, 3), "MISO", dx=-4)
    stub_label(sch, conn_1xn_pin(j6_pos, 6, 4), "SCK", dx=-4)
    stub_label(sch, conn_1xn_pin(j6_pos, 6, 5), "SPI_CS0", dx=-6)
    stub_pwr(sch, conn_1xn_pin(j6_pos, 6, 6), "power:GND", pwr, dx=-4, dy=0)

    j7_pos = (bx + 64, by + 12)
    j7 = sch.components.add(
        "Connector_Generic:Conn_01x08", "J7", "GPIO", position=j7_pos
    )
    j7.footprint = FP_CONN_1X08
    stub_pwr(sch, conn_1xn_pin(j7_pos, 8, 1), "power:+3V3", pwr, dx=-4, dy=0)
    for i in range(6):
        nc(sch, conn_1xn_pin(j7_pos, 8, i + 2))
    stub_pwr(sch, conn_1xn_pin(j7_pos, 8, 8), "power:GND", pwr, dx=-4, dy=0)


def place_decoupling_block(sch, bx: int, by: int, pwr: dict) -> None:
    """Place 4x 100nF decoupling caps for CM4."""
    for i in range(4):
        pos = (bx + i * 8, by + 4)
        c = sch.components.add("Device:C", f"C{i + 5}", "100nF", position=pos)
        c.footprint = FP_C_0402
        stub_pwr(sch, c_pin(pos, 1), "power:+3V3", pwr, dy=-4)
        stub_pwr(sch, c_pin(pos, 2), "power:GND", pwr, dy=4)
