# AUTO-GENERATED by /generate-schematic — do not edit manually.
# This file is replaced entirely each time the skill runs for a new circuit.
"""CM4 carrier board schematic generation using kicad-sch-api.

Reads layout_spec.yaml for sheet size, title, and block positions.
"""

from pathlib import Path

import kicad_sch_api as ksa
import yaml

from cad.schematic.sch_comms import place_rs485_block, place_usb_uart_block
from cad.schematic.sch_io import place_decoupling_block, place_io_block
from cad.schematic.sch_mcu import place_cm4_block
from cad.schematic.sch_power import place_power_block

LAYOUT_SPEC_PATH = Path("cad/layout_spec.yaml")
SCHEMATIC_PATH = "cad/cm4_carrier.kicad_sch"


def _load_spec() -> dict:
    return yaml.safe_load(LAYOUT_SPEC_PATH.read_text())


def build_schematic() -> None:
    """Generate complete CM4 carrier board schematic."""
    spec = _load_spec()
    ksa.use_grid_units(True)
    sch = ksa.create_schematic(spec["title"])
    sch.set_paper_size(spec.get("sheet_size", "A3"))
    sch.set_title_block(title=spec["title"], company="Engineering With AI", rev="1.0")

    pwr = {"n": 1, "flg": 1}
    mx, my = 30, 28

    place_power_block(sch, bx=mx, by=my, pwr=pwr)
    place_cm4_block(sch, j2_pos=(mx + 74, my + 24), pwr=pwr)
    place_rs485_block(sch, bx=mx + 104, by=my, pwr=pwr)
    place_usb_uart_block(sch, bx=mx, by=my + 56, pwr=pwr)
    place_io_block(sch, bx=mx + 104, by=my + 54, pwr=pwr)
    place_decoupling_block(sch, bx=mx + 104, by=my + 92, pwr=pwr)

    sch.save_as(SCHEMATIC_PATH)


if __name__ == "__main__":
    build_schematic()
    print(f"Schematic: {SCHEMATIC_PATH}")
