"""Place PCB footprints from pcb_placement.yaml.

Reads cached positions, moves footprints, clears stale traces, draws outline.
Positions are generated by the /layout-pcb skill, not computed here.
"""

from pathlib import Path

import pcbnew
import yaml

PLACEMENT_FILE = Path("cad/pcb_placement.yaml")
PCB_PATH = Path("cad/cm4_carrier.kicad_pcb")


def place_footprints() -> None:
    """Place all footprints and draw board outline."""
    placement = yaml.safe_load(PLACEMENT_FILE.read_text())
    if not placement or "blocks" not in placement:
        raise SystemExit("No blocks in pcb_placement.yaml — run /layout-pcb first")

    ox, oy = placement["board_origin"]
    bw, bh = placement["board_size"]

    board = pcbnew.LoadBoard(str(PCB_PATH))

    # Reason: stale traces from prior routing corrupt re-routing
    tracks = list(board.GetTracks())
    zones = list(board.Zones())
    for t in tracks:
        board.Remove(t)
    for z in zones:
        board.Remove(z)
    if tracks or zones:
        print(f"Cleared {len(tracks)} tracks, {len(zones)} zones")

    placed = 0
    for block in placement["blocks"].values():
        for ref, (x, y, rot) in block["components"].items():
            fp = board.FindFootprintByReference(ref)
            if fp is None:
                print(f"WARNING: {ref} not found on board")
                continue
            fp.SetPosition(
                pcbnew.VECTOR2I(pcbnew.FromMM(ox + x), pcbnew.FromMM(oy + y))
            )
            fp.SetOrientationDegrees(rot)
            placed += 1

    has_outline = any(s.GetLayer() == pcbnew.Edge_Cuts for s in board.GetDrawings())
    if not has_outline:
        _draw_outline(board, ox, oy, bw, bh)
        print(f"Drew {bw}x{bh}mm board outline")

    board.Save(str(PCB_PATH))
    print(f"Placed {placed} footprints, saved {PCB_PATH}")


def _draw_outline(board, ox: float, oy: float, w: float, h: float) -> None:
    """Draw rectangular board outline on Edge.Cuts layer."""
    corners = [
        ((ox, oy), (ox + w, oy)),
        ((ox + w, oy), (ox + w, oy + h)),
        ((ox + w, oy + h), (ox, oy + h)),
        ((ox, oy + h), (ox, oy)),
    ]
    for (x1, y1), (x2, y2) in corners:
        seg = pcbnew.PCB_SHAPE(board)
        seg.SetShape(pcbnew.SHAPE_T_SEGMENT)
        seg.SetStart(pcbnew.VECTOR2I(pcbnew.FromMM(x1), pcbnew.FromMM(y1)))
        seg.SetEnd(pcbnew.VECTOR2I(pcbnew.FromMM(x2), pcbnew.FromMM(y2)))
        seg.SetLayer(pcbnew.Edge_Cuts)
        seg.SetWidth(pcbnew.FromMM(0.1))
        board.Add(seg)


if __name__ == "__main__":
    place_footprints()
